-- Complete schema recreation script for new Supabase project
-- Run this in your new project's SQL Editor

-- 1. Create custom types
CREATE TYPE public.user_role AS ENUM ('admin', 'tenant');

-- 2. Create tables in order (independent tables first)

-- Tenants table
CREATE TABLE public.tenants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- User roles table
CREATE TABLE public.user_roles (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid NOT NULL,
    role user_role DEFAULT 'tenant'::user_role NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- Email threads table
CREATE TABLE public.email_threads (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    subject text NOT NULL,
    participant_email text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Email messages table
CREATE TABLE public.email_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    thread_id uuid NOT NULL,
    direction text NOT NULL,
    from_email text NOT NULL,
    to_email text NOT NULL,
    body text,
    attachments jsonb DEFAULT '[]'::jsonb NOT NULL,
    seen boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Inbox messages table
CREATE TABLE public.inbox_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    channel text NOT NULL,
    from_msisdn text NOT NULL,
    to_msisdn text NOT NULL,
    body text,
    profile_name text,
    twilio_sid text,
    media jsonb DEFAULT '[]'::jsonb,
    raw jsonb,
    seen boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Outbound messages table
CREATE TABLE public.outbound_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    channel text DEFAULT 'whatsapp'::text NOT NULL,
    from_msisdn text NOT NULL,
    to_msisdn text NOT NULL,
    body text NOT NULL,
    media jsonb DEFAULT '[]'::jsonb NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    twilio_sid text,
    error text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Tickets table
CREATE TABLE public.tickets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid,
    title text NOT NULL,
    description text,
    category text DEFAULT 'general'::text NOT NULL,
    priority text DEFAULT 'medium'::text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    property_address text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. Create conversation_messages view
CREATE VIEW public.conversation_messages AS
SELECT 
    im.id,
    'inbound'::text AS direction,
    im.channel,
    im.from_msisdn AS counterparty,
    im.to_msisdn AS our_number,
    im.body,
    im.twilio_sid,
    im.media,
    im.created_at,
    NULL::text AS status
FROM public.inbox_messages im

UNION ALL

SELECT 
    om.id,
    'outbound'::text AS direction,
    om.channel,
    om.to_msisdn AS counterparty,
    om.from_msisdn AS our_number,
    om.body,
    om.twilio_sid,
    om.media,
    om.created_at,
    om.status
FROM public.outbound_messages om
ORDER BY created_at;