// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfyvtmaipbsiveumbxwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmeXZ0bWFpcGJzaXZldW1ieHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTIwMDEsImV4cCI6MjA3MTM4ODAwMX0.UpNgShA7jWSQsXhUne3LP8OBHBNCl1dmbiD2AGx6sVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});